# AnyarAppIcon.cmake — embed an application icon into a LibAnyar executable.
#
#   include(AnyarAppIcon)
#   anyar_app_icon(myapp "${CMAKE_CURRENT_SOURCE_DIR}/icon.ico")
#
# Windows: compiles a resource script that stores <icon>.ico as ICON resource
# 32512 (IDI_APPLICATION).  webview/webview loads exactly that id for its
# window class, so one resource sets the title-bar, taskbar, Alt-Tab,
# shortcut and Explorer icon.  `anyar build` converts icon.png → .ico and
# passes it as ANYAR_APP_ICON.
#
# Other platforms: no-op (Linux packaging uses the icon file directly; macOS
# bundles are Phase 7.2).

function(anyar_app_icon target icon)
    if(NOT WIN32)
        return()
    endif()
    get_filename_component(icon_abs "${icon}" ABSOLUTE)
    if(NOT EXISTS "${icon_abs}")
        message(WARNING "anyar_app_icon: ${icon_abs} not found — no icon embedded")
        return()
    endif()
    get_filename_component(ext "${icon_abs}" EXT)
    string(TOLOWER "${ext}" ext)
    if(NOT ext STREQUAL ".ico")
        message(WARNING "anyar_app_icon: ${icon_abs} is not an .ico — no icon embedded "
                        "(`anyar build` converts PNG for you)")
        return()
    endif()

    # rc.exe wants forward slashes or escaped backslashes in quoted paths.
    file(TO_CMAKE_PATH "${icon_abs}" icon_rc_path)
    set(rc "${CMAKE_CURRENT_BINARY_DIR}/${target}_app_icon.rc")
    file(WRITE "${rc}"
        "// Generated by anyar_app_icon() — do not edit.\n"
        "// 32512 = IDI_APPLICATION: the id webview/webview loads for its windows.\n"
        "32512 ICON \"${icon_rc_path}\"\n")
    target_sources(${target} PRIVATE "${rc}")
    # Rebuild the resource when the icon changes.
    set_source_files_properties("${rc}" PROPERTIES OBJECT_DEPENDS "${icon_abs}")
endfunction()
